### ISSUE TITLE
Which version of colmap will this support?

### ISSUE THREAD

**Issue by reynoldscem-oculo** [cvg/limap#109]
Hi,

I'm very much looking forward to the release of Hybrid SfM. I was wondering, which version of colmap will ultimately be supported? Or will this be upstsreamed into the colmap repo?

Specifically I am curious if we'll see line+point based SfM with their new pose prior support?

**Comment by B1ueber2y** [comment]
Hey. We will support the newest colmap, as already being migrated in this limap repo from https://github.com/cvg/limap/pull/98. This is also the major blocker on releasing the hybrid sfm as there are still some efforts needed for the migration to make a clean release.

It will not be upstreamed into the colmap repo. Rather, it will stay in this limap repo with COLMAP being the dependency with FetchContent. We will try to support as many features as possible from COLMAP.

**Comment by reynoldscem-oculo** [comment]
Amazing, thank you!
