### ISSUE TITLE
install requirements.txt error

### ISSUE THREAD

**Issue by WHU-Dewran** [cvg/limap#26]
Hi, I am quite interested in your work which is excellent.
I am trying to run your code, but there occur some installing problems that I could not deal with as I am new to Linux and CUDA.
python -m pip install -r requirements.txt this step occurs error:
`ERROR: Directory './third-party/pytlsd' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
`
Could you please help me out?

**Comment by MarkYu98** [comment]
Did you run `git submodule update --init --recursive`? The submodules need to be recursively pulled after cloning the repository.

**Comment by WHU-Dewran** [comment]
I am not sure about the steps after running `sudo apt-get install libhdf5-dev` 
Do I need to download the code at first and cd in it, then run `git submodule update --init --recursive`?

**Comment by MarkYu98** [comment]
Yes you need to run `git clone https://github.com/cvg/limap.git` first to get the code, and then `cd limap` and `git submodule update --init --recursive`.

**Comment by WHU-Dewran** [comment]
I just follow the steps like you said, but everytime I run the code`python -m pip install -r requirements.txt`
occurs the error:
`ERROR: Directory './third-party/pytlsd' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
`
Is it normal that there is nothing in `./third-party/pytlsd` nor other subfolders?

**Comment by MarkYu98** [comment]
Has your `git submodule update --init --recursive` succeeded? Could you manually check what's in `./third-party/pytlsd`?

**Comment by WHU-Dewran** [comment]
Thank you so much for your patience!! I solve the problem, it just did not succeed actually.
But there occurs a new problem when running `python -m pip install -r requirements.txt`
`Processing ./third-party/pytlsd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./third-party/hawp
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-k9a8m7b3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-k9a8m7b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-k9a8m7b3/pip-egg-info
         cwd: /tmp/pip-req-build-k9a8m7b3/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-k9a8m7b3/setup.py", line 33, in <module>
        packages=find_packages(['hawp']),
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 69, in find
        return list(cls._find_packages_iter(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 80, in _find_packages_iter
        for root, dirs, files in os.walk(where, followlinks=True):
      File "/usr/lib/python3.8/os.py", line 339, in walk
        top = fspath(top)
    TypeError: expected str, bytes or os.PathLike object, not list
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
Is it because of the version? My CUDA is 11.6.

**Comment by franklhj** [comment]
Hi, can you tell me how you run `git submodule update-init-recursive` successfully?

**Comment by Lin239522** [comment]
> 非常感谢您的耐心等待！！我解决了这个问题，但实际上并没有成功。 但是运行的时候又出现了新的问题`python -m pip install -r requirements.txt` `Processing ./third-party/pytlsd Installing build dependencies ... done Getting requirements to build wheel ... done Preparing wheel metadata ... done Processing ./third-party/hawp ERROR: Command errored out with exit status 1: command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-k9a8m7b3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-k9a8m7b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-k9a8m7b3/pip-egg-info cwd: /tmp/pip-req-build-k9a8m7b3/ Complete output (11 lines): Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-req-build-k9a8m7b3/setup.py", line 33, in <module> packages=find_packages(['hawp']), File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 69, in find return list(cls._find_packages_iter( File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 80, in _find_packages_iter for root, dirs, files in os.walk(where, followlinks=True): File "/usr/lib/python3.8/os.py", line 339, in walk top = fspath(top) TypeError: expected str, bytes or os.PathLike object, not list ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ` 难道是版本的原因？我的CUDA是11.6。

您好~我遇到了和您相同的报错，请问您是如何解决的呢
