### ISSUE TITLE
About ImportError:undefined symbol

### ISSUE THREAD

**Issue by WHU-Dewran** [cvg/limap#30]
Hi, after finishing all the requirements successfully, I run `python -c "import limap"`, occurs the error:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dewran/limap/limap/__init__.py", line 3, in <module>
    from _limap import *
ImportError: /lib/x86_64-linux-gnu/libfreeimage.so.3: undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0`
I have no idea how to deal with it, could you please help me?
My cuda version is 11.5 and have _Anaconda3-2023.03_ installed.

**Comment by B1ueber2y** [comment]
Hey. Yes I have encountered this one before! (seldomly I know what exactly is happening in the raised issue :)

You can look into this: https://github.com/colmap/colmap/issues/188

I think "conda uninstall libtiff" could be the easiest way to solve it, as it is not needed in limap from what I remembered.
