### ISSUE TITLE
About projecting 3D line segments into 2D images.

### ISSUE THREAD

**Issue by ccy-ustb** [cvg/limap#32]
hello，I would like to ask a question：
Is it based on the principle of perspective projection to project the two endpoints of a 3D line segment into a 2D image, and then connect them?
eg：(R * X_start_In3DWorld+T)*intrinsic_matrix=X_start_InImage,(R * X_end_In3DWorld+T)*intrinsic_matrix=X_end_InImage
And R,T is the corresponding camera Rotation matrix and translation vector, intrinsic_ Matrix is the corresponding camera internal parameter matrix.
I think your code seems to do this.

**Comment by B1ueber2y** [comment]
We follow the basic principle of perspective projection. that is, K(Rx + T) corresponds to the homogenous coordinate of the 2D projection, where K is the intrinsic matrix, and [R, T] are the extrinsics.

Thanks!
