### ISSUE TITLE
How to reconstruct line mapping on own dataset

### ISSUE THREAD

**Issue by WHU-Dewran** [cvg/limap#33]
Hi! Now I have colmap results of my own dataset, how can I reconstruct line map?
Am I gonna run triangulation.py on Hypersim?

**Comment by WHU-Dewran** [comment]
Which is the COLMAP compatible runner to run LIMAP?

**Comment by B1ueber2y** [comment]
Hi, thanks for the interest! This is the interface for running LIMAP on COLMAP reconstruction: https://github.com/cvg/limap/blob/main/runners/colmap_triangulation.py

You can use "python runners/colmap_triangulation.py -a ${PATH_TO_YOUR_COLMAP_FILE}" to run the basic triangulation. We are working hard on the documentations which will be released very soon. 

Thanks a lot!

**Comment by WHU-Dewran** [comment]
> Hi, thanks for the interest! This is the interface for running LIMAP on COLMAP reconstruction: https://github.com/cvg/limap/blob/main/runners/colmap_triangulation.py
> 
> You can use "python runners/colmap_triangulation.py -a ${PATH_TO_YOUR_COLMAP_FILE}" to run the basic triangulation. We are working hard on the documentations which will be released very soon.
> 
> Thanks a lot!

Thank you so much!
I have successfully reconstructed line map on my dataset.
