### ISSUE TITLE
pip install -Ive 

### ISSUE THREAD

**Issue by WHU-Dewran** [cvg/limap#48]
When I run `python -m pip install -Ive . `, occurs the error:
` In file included from /home/rylynn/limap-initial/limap/base/transforms.cc:1:
    /home/rylynn/limap-initial/limap/base/transforms.h:4:10: fatal error: colmap/base/pose.h: No such file or directory
        4 | #include <colmap/base/pose.h>
          |          ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:104: limap/CMakeFiles/limap.dir/base/transforms.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    In file included from /home/rylynn/limap-initial/limap/base/camera.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    In file included from /home/rylynn/limap-initial/limap/base/camera_view.h:16,
                     from /home/rylynn/limap-initial/limap/base/linebase.h:13,
                     from /home/rylynn/limap-initial/limap/base/line_dists.h:10,
                     from /home/rylynn/limap-initial/limap/base/line_dists.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    In file included from /home/rylynn/limap-initial/limap/base/camera_view.h:16,
                     from /home/rylynn/limap-initial/limap/base/camera_view.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:90: limap/CMakeFiles/limap.dir/base/camera.cc.o] Error 1
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:118: limap/CMakeFiles/limap.dir/base/camera_view.cc.o] Error 1
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:188: limap/CMakeFiles/limap.dir/base/line_dists.cc.o] Error 1
    In file included from /home/rylynn/limap-initial/limap/base/camera_view.h:16,
                     from /home/rylynn/limap-initial/limap/base/linebase.h:13,
                     from /home/rylynn/limap-initial/limap/base/line_linker.h:8,
                     from /home/rylynn/limap-initial/limap/base/line_linker.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:202: limap/CMakeFiles/limap.dir/base/line_linker.cc.o] Error 1
    In file included from /home/rylynn/limap-initial/limap/base/image_collection.h:18,
                     from /home/rylynn/limap-initial/limap/base/image_collection.cc:1:
    /home/rylynn/limap-initial/limap/base/transforms.h:4:10: fatal error: colmap/base/pose.h: No such file or directory
        4 | #include <colmap/base/pose.h>
          |          ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:132: limap/CMakeFiles/limap.dir/base/image_collection.cc.o] Error 1
    In file included from /home/rylynn/limap-initial/limap/base/camera_view.h:16,
                     from /home/rylynn/limap-initial/limap/base/linetrack.h:14,
                     from /home/rylynn/limap-initial/limap/base/linetrack.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:174: limap/CMakeFiles/limap.dir/base/linetrack.cc.o] Error 1
    In file included from /home/rylynn/limap-initial/limap/base/camera_view.h:16,
                     from /home/rylynn/limap-initial/limap/base/linebase.h:13,
                     from /home/rylynn/limap-initial/limap/base/linebase.cc:1:
    /home/rylynn/limap-initial/limap/base/camera.h:16:10: fatal error: colmap/base/camera.h: No such file or directory
       16 | #include <colmap/base/camera.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [limap/CMakeFiles/limap.dir/build.make:160: limap/CMakeFiles/limap.dir/base/linebase.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:667: limap/CMakeFiles/limap.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/rylynn/limap-initial/setup.py", line 68, in <module>
        setup(
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
        self._build_extensions_serial()
      File "/home/rylynn/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/rylynn/limap-initial/setup.py", line 61, in build_extension
        subprocess.check_call(
      File "/home/rylynn/anaconda3/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--parallel 8']' returned non-zero exit status 2.
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/rylynn/anaconda3/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/rylynn/limap-initial/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/rylynn/limap-initial/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`
Does anyone know what is going on here? please ask for help!!

**Comment by dscho15** [comment]
What was the fix?

**Comment by WHU-Dewran** [comment]
> What was the fix?

If you run `python setup.py develop`, you will get more details.
After running `python setup.py develop`, I found that it was COLMAP configuration caused the error.
Then I just retried the installation from the very beginning and carefully followed the instructions especially installing COLMAP.
Finally, it worked.
Ohh, I suggest that you install colmap-3.8 instead of 3.9.
