### ISSUE TITLE
Hard to make enough triangulation

### ISSUE THREAD

**Issue by ComputerMath** [cvg/limap#58]
Hello, I did the line triangulation from the colmap's estimated pose with my own dataset, but it doesn't seem that triangulation work well although there are enough highly similar detected 2D line when I compared many images. 

Although I changed the extractor and matching in the cfg's default.yaml file, it still doesn't make many 3D line.
(e.g. wireframe + gluestick -> superpoint endpoint + superglue endpoint)

Is there any solution by modifying the cfg's default values to make more 3D lines?

![제목 없음](https://github.com/cvg/limap/assets/29303833/dd5a3197-3755-4a03-b2aa-3b381e65227d)
![제목 없음](https://github.com/cvg/limap/assets/29303833/fc8cd91a-d116-4545-ba2c-345a5db2f772)

(green line: detected lines by DeepLSD, blue line: triangulated lines)

Thanks in advance :)

**Comment by B1ueber2y** [comment]
Hello. This case might be very challenging due to extremely small triangulation angle with forward motion, so the lines far from the cameras will be very difficult to triangulate. Nonetheless, there might be a way to triangulate those close-by lines, while it also depends on the coverage and trajectories of your input images. Thanks

**Comment by ComputerMath** [comment]
Hello, Thanks for your answering!
I understand your answer, but just out of pure curiosity, can you tell me why it is hard to make it triangulated in detail?
You can just answer by saying the sentences or equation in the limap paper, or simple example. 
Thanks

**Comment by B1ueber2y** [comment]
Hello. Generally small triangulation angle makes the triangulation difficult for both points and lines. Specifically, for points, when the triangulation angle is small, the intersection of two rays becomes ill-posed. And for lines, similarly, small triangulation angle between the ray and the backprojected plane (from the second image) makes it triangulation very unstable. Thus, in practice a threshold on the triangulation angle is needed to enable stability on the triangulation. Thanks
