### ISSUE TITLE
A possible bug in calculating the score between two lines?

### ISSUE THREAD

**Issue by bxloong** [cvg/limap#71]
Hello, thanks for the wonderful work!

I wonder if there is a possible bug in calculating the score between two lines in the code snippet below.

https://github.com/cvg/limap/blob/57895c5bd3fab04f9ad272a27ca98bdc2b799a00/limap/base/line_linker.h#L40C5-L40C67
```C++
double multiplier() const { return get_multiplier(score_th); }
```

https://github.com/cvg/limap/blob/57895c5bd3fab04f9ad272a27ca98bdc2b799a00/limap/base/line_linker.cc#L11C1-L22C2

```C++
double get_multiplier(const double& score_th) {
    // exp(- (val / sigma)^2 / 2.0) >= 0.5 <--> val <= 1.1774100 sigma
    return sqrt(-log(score_th) * 2.0);
}


double LineLinker2d::compute_score_angle(const Line2d& l1, const Line2d& l2) const {
    double angle = compute_angle<Line2d>(l1, l2);
    double score = expscore(angle, config.th_angle * config.multiplier());
    if (score < config.score_th)
        score = 0.0;
    return score;
}
```

Should `double score = expscore(angle, config.th_angle * config.multiplier());`  be modified to `double score = expscore(angle, config.th_angle / config.multiplier());`  to ensure that when `angle` equals `config.th_angle`, the `score` precisely equals 0.5 (assuming the `score_th` is set to 0.5)? 

Was this your initial intention?

Looking forward to your reply :)

**Comment by B1ueber2y** [comment]
Hey,

Indeed this is a bug. Thanks a lot for the catch! This has been fixed now: https://github.com/cvg/limap/commit/e15088a41ccca945a32624c470450e46663a05b6 

Best,
Shaohui
