### ISSUE TITLE
A possible bug in calculating "innerseg" between two lines?

### ISSUE THREAD

**Issue by bxloong** [cvg/limap#72]
Hello, thanks for the nice work!

There may be a bug in calculating "innerseg" between two lines.

In the comments on the following code, it appears the author intends to unproject the two endpoints of `l1` to `l2`. However, the actual code appears to project some vectors onto `l1`, which doesn't seem to get "innerseg".

https://github.com/cvg/limap/blob/e15088a41ccca945a32624c470450e46663a05b6/limap/base/line_dists.h#L147C1-L165C2

```c++
// innerseg
template <typename LineType>
bool get_innerseg(const LineType& l1, const LineType& l2, LineType& innerseg) {
    // unproject the two endpoints of l1 to l2 and select the inner seg along l2
    // return false if there is no overlap between the unprojection and l2
    auto l1_dir = l1.direction();
    double denom = (l2.end - l2.start).dot(l1_dir);
    double nume_start = (l1.start - l2.start).dot(l1_dir);
    double t1 = nume_start / (denom + EPS);
    double nume_end = (l1.end - l2.start).dot(l1_dir);
    double t2 = nume_end / (denom + EPS);
    if (t1 > t2)
        std::swap(t1, t2);
    if (t1 >= 1.0 || t2 <= 0.0) 
        return false;
    innerseg.start = l2.start + (l2.end - l2.start) * std::max(t1, 0.0);
    innerseg.end = l2.start + (l2.end - l2.start) * std::min(t2, 1.0);
    return true;
}
```

**Comment by B1ueber2y** [comment]
Hey thanks for the interest. I double checked on the implementation and did not find any issue from my side. 

The "innerseg" operation involves unprojecting the two endpoints of l_1 to l_2 and computing the intersection. This can be done by projecting the two endpoints of l_2 onto l_1 and set them as 0.0 and 1.0, and see how the two endpoints of l_1 locate between the two projections (i.e. t1 and t2 in the code). In the end, the innerseg is computed on l_2 with the intersection computed using t1 and t2, as implemented in the code. 

Please let me know if there are any confusion. Thanks again!

**Comment by bxloong** [comment]
Thank you very much for your reply. I still have some confusion.

In your response, you mentioned "This can be done by projecting the two endpoints of l_2 onto l_1". However, as shown in the code, `(l1.start - l2.start)` and `(l1.end - l2.start)` are projected onto l_1. This doesn't seem to project the two endpoints of l_2 onto l_1.

In the Section 3.2 in the main paper "3D Line Mapping Revisited", when it comes to"InnerSeg distance", the authors mentioned "the endpoints of L_1 are perpendicularly unprojected to L_2.  If they fall outside of L2, we clip them to the closest endpoint of L2. By doing this in both directions, we can define two inner segments (see Fig. 3(c)), and the InnerSeg distance as the maximum distance between their endpoints.".  

According to my current understanding, calculating the innerseg of l_1 on l_2 should project the endpoints of l_1 onto l_2 and then clip the projection line based on the endpoints of l_2 to get the innerseg, which can be translated into the following code.

```C++
  // innerseg
  template <typename LineType>
  bool get_innerseg(const LineType &l1, const LineType &l2, LineType &innerseg)
  {
    // unproject the two endpoints of l1 to l2 and select the inner seg along l2
    // return false if there is no overlap between the unprojection and l2
    const auto l2_dir = l2.direction(); // (l2.end - l2.start).normalized()
    const double l2_length = l2.length();
    // assuming l2.start is the origin in 1D coordinates,
    // and the positive axis goes from l2.start to l2.end
    double t1 = (l1.start - l2.start).dot(l2_dir);
    double t2 = (l1.end - l2.start).dot(l2_dir);
    if (t1 > t2)
      std::swap(t1, t2);
    if (t1 >= l2_length || t2 <= 0.0) // no overlap
      return false;
    innerseg.start = l2.start + l2_dir * std::max(t1, 0.0);
    innerseg.end = l2.start + l2_dir * std::min(t2, l2_length);
    return true;
  }
```

I'm very curious if my understanding is correct. Thanks again for your reply!

**Comment by B1ueber2y** [comment]
For the computation of "innerseg" we apply the operation of unprojection rather than projection, as described in the paper. This is further illustrasted in Fig. 3(c) on arxiv. The 2D unprojection is defined as extending the point on the line with the orthogonal direction, and compute intersection with the other line, which can be also computed with inverse projection as implemented here. The benefits of unprojection over projection on computing the distance is mostly on handling lines with extremely different length, and is discussed in Sec. F.3 in Appendix.

**Comment by bxloong** [comment]
I understand. Thank you for your reply.

 I will close the issue because there are no bugs.
