### ISSUE TITLE
Questions about the parameter `add_halfpix`.

### ISSUE THREAD

**Issue by xulongbai** [cvg/limap#81]
Hi, thanks for the great work!

I have two questions about the parameter `add_halfpix`.

- Why is `add_halfpix` set to `False` in the Hypersim dataset but `True` in the Tanks and Temples dataset? Both datasets seem to use the DeepLSD line detector by default.
- Is it necessary to add half a pixel for the vanishing point?

Looking forward to your reply :)

**Comment by B1ueber2y** [comment]
The option is more for the convention to define pixel coordinates (to be at the corner or at the center of the pixel), where in COLMAP convention there is generally an half pixel offset while in Hypersim it is not. Empirically this does not make a huge difference in my experience.

**Comment by xulongbai** [comment]
Hi Shaohui,

Thank you for your thoughtful response. After reviewing the code, I tentatively believe that adding half a pixel may not pertain to the dataset itself but rather to the coordinate system used for the detected 2D line segments. This observation holds true for both the Hypersim and Tanks and Temples datasets, as they rely on COLMAP's camera model within LIMAP.

Regarding the coordinate system for 2D line segments, I reached out to Rémi Pautrat, the first author of [DeepLSD](https://github.com/cvg/DeepLSD), via email some time ago. Rémi, who contributed to the development of both [DeepLSD](https://github.com/cvg/DeepLSD) (the `deeplsd` detector in LIMAP) and [pytlsd](https://github.com/iago-suarez/pytlsd) (the `lsd` detector in LIMAP), clarified that the coordinate origins for 2D line segments detected by both [DeepLSD](https://github.com/cvg/DeepLSD) and [pytlsd](https://github.com/iago-suarez/pytlsd) are located at the top-left corner of the top-left pixel in the image. This convention aligns with the COLMAP coordinate system. I am deeply grateful to Rémi Pautrat for his assistance.

Based on this, I believe that using [DeepLSD](https://github.com/cvg/DeepLSD) and [pytlsd](https://github.com/iago-suarez/pytlsd) with any dataset should not necessitate adding half a pixel.

I eagerly await your thoughts on this matter. Thank you once again for your time and expertise! (And my apologies for inadvertently closing the issue.)

Best,
Xulong Bai
